# Generated by Django 5.2.17 on 2026-08-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='connect',
        ),
    ]
