# Generated by Django 5.2.17 on 2026-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_contact_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
