# Generated by Django 5.2.17 on 2026-08-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_connect_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connect',
            options={'ordering': ['-created_date']},
        ),
    ]
