# Generated by Django 5.2.17 on 2026-08-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_connect_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='connect',
            new_name='contact',
        ),
    ]
