# Generated by Django 5.2.17 on 2026-08-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_connect_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
