# Generated by Django 5.2.17 on 2026-08-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_counted_view_post_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/comment-author-01.jpg', upload_to='images/'),
        ),
    ]
